In [1]:
import pandas as pd

In [2]:
# Series in pandas
s = pd.Series([23, 24, 25, 26])
print(s)
print(type(s))

# Indexing
print(s[0])    # 23
print(s[2])    # 25

print(s.index)     # all labels


# Custom Indexing
s2 = pd.Series([23, 24, 25, 26], index = ["Adam", "Eve", "Charlie", "Bob"])
print(s2["Eve"])    # 24
print(s2["Bob"])    # 26

# Vectorized Operations
s1 = pd.Series([1, 2, 3])
s2 = pd.Series([4, 5, 6])

print(s1 + s2)

# Mutable Values but immutable size
s = pd.Series([1, 2, 3, 4, 5])
s[0] = 100

print(s)

changed_s = s.drop(1)
print(changed_s)
print(s)

0    23
1    24
2    25
3    26
dtype: int64
<class 'pandas.core.series.Series'>
23
25
RangeIndex(start=0, stop=4, step=1)
24
26
0    5
1    7
2    9
dtype: int64
0    100
1      2
2      3
3      4
4      5
dtype: int64
0    100
2      3
3      4
4      5
dtype: int64
0    100
1      2
2      3
3      4
4      5
dtype: int64

In [3]:
# DataFrame in pandas - using dictionary
info = {
    "Name" : ["Adam", "Eve", "Bob"],
    "Marks" : [78, 99, 85],
    "Grade" : ['B', 'O', 'A']
}

df = pd.DataFrame(info)
print(df)
print(type(df))

print(df.index)        # row labels
print(df.columns)      # column labels

   Name  Marks Grade
0  Adam     78     B
1   Eve     99     O
2   Bob     85     A
<class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Marks', 'Grade'], dtype='object')

In [4]:
df

   Name  Marks Grade
0  Adam     78     B
1   Eve     99     O
2   Bob     85     A

In [5]:
# DataFrom using Lists
l = [["Adam", 96], ["Eve", 75], ["Bob", 82], ["Charlie", 92]]
df = pd.DataFrame(l, columns=["Name", "Marks"])
print(df)

      Name  Marks
0     Adam     96
1      Eve     75
2      Bob     82
3  Charlie     92

In [6]:
# DataFrom using Numpy array

import numpy as np
np_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df = pd.DataFrame(np_arr, columns=["Col1", "Col2", "Col3"])
print(df)

   Col1  Col2  Col3
0     1     2     3
1     4     5     6
2     7     8     9

In [7]:
# pandas with csv files
data = pd.read_csv("employee_data.csv")
print(data, type(data))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [8]:
# pandas with json files
import json
json_data = pd.read_json("employee_data.json")
print(json_data, type(json_data))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [9]:
# DataFrame Methods
df = pd.read_csv("employee_data.csv")

print(df.head())
print(df.tail())
print(df.sample())
print(df.info())
print(df.shape)
print(df.describe())
print(df.columns)
print(df.nunique())

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
   ID    Name  Age Department  Salary
5   6   Frank   29    Finance   50000
6   7   Grace   41         HR   82000
7   8  Hannah   26  Marketing   47000
8   9     Ian   35         IT   75000
9  10   Julia   30    Finance   60000
   ID    Name  Age Department  Salary
7   8  Hannah   26  Marketing   47000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes
None
(10, 5)
             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000
Index(['ID', 'Name', 'Age', 'Department', 'Salary'], dtype='object')
ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [10]:
df = pd.read_csv("globalAirQuality.csv")
print(type(df))

#print(df.head())
#print(df.tail())
print(df.describe())

<class 'pandas.core.frame.DataFrame'>
           latitude     longitude          pm25          pm10           no2  \
count  18000.000000  18000.000000  18000.000000  18000.000000  18000.000000
mean      23.065980     37.655560     40.369131     70.152228     32.055176
std       26.156536     78.600701     17.647450     24.999440     13.820680
min      -37.814000   -123.121000      0.025000      0.061000      0.013000
25%       12.972000      2.352000     27.904500     53.125500     22.362500
50%       29.232000     42.146000     40.286500     69.961000     32.019500
75%       41.008000    103.820000     52.436250     87.256500     41.364250
max       60.170000    174.763000    115.683000    161.810000     90.019000

                so2            o3            co           aqi   temperature  \
count  18000.000000  18000.000000  18000.000000  18000.000000  18000.000000
mean       6.035508     48.065100      0.800595    104.645556     21.510251
std        2.454790     14.950849      0.250254     25.616070      9.509444
min        0.003000      0.114000      0.000000     16.000000      5.000000
25%        4.360750     38.028500      0.633000     87.000000     13.357750
50%        6.026000     48.142000      0.800500    103.000000     21.455500
75%        7.715250     58.258500      0.969000    121.000000     29.688250
max       16.559000    103.016000      1.832000    231.000000     37.998000

           humidity    wind_speed
count  18000.000000  18000.000000
mean      57.714351      5.283910
std       18.844908      2.741712
min       25.002000      0.500000
25%       41.320000      2.937000
50%       57.847000      5.297000
75%       74.234750      7.662000
max       89.997000      9.999000

In [11]:
# Selecting Data

# Select columns
df["country"]
df[["city", "aqi"]]

# Select rows (by label)
df.loc[0]             # 1st row (by label)
df.loc[0:3]           # row0 to row3 - both inclusive in loc

# Select rows (by index)
df.iloc[0]            # 1st row 
df.iloc[4:7]          # 1st row 

# Select rows & columns
df.loc[0, "country"]  # 0th row & specific column
df.iloc[0, 2]         # 1th row & 3rd column (by position)

#df.iloc[0:3, 2]
df.loc[0:2, ["country", "aqi"]]

# Select single scalar value
df.at[0, "city"]
df.iat[0, 2]

'New York'

In [12]:
# Filtering Data
df[df["aqi"] > 100]
df[df["aqi"] > 100][["city", "aqi"]]

           city  aqi
0      New York  108
3      New York  158
6      New York  155
7      New York  115
8      New York  121
...         ...  ...
17991    Zurich  104
17993    Zurich  153
17995    Zurich  103
17996    Zurich  105
17997    Zurich  122

[9721 rows x 2 columns]

In [13]:
# Filtering Data
df[df["aqi"] > 100]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
6,2025-11-05 00:25:17.554219,US,New York,40.713,-74.006,77.690,65.198,20.302,7.641,62.687,0.734,155,36.729,47.651,4.542
7,2025-11-05 01:25:17.554219,US,New York,40.713,-74.006,57.816,111.709,34.533,6.945,41.304,0.771,115,37.891,53.314,7.605
8,2025-11-05 02:25:17.554219,US,New York,40.713,-74.006,60.914,44.775,40.936,6.779,36.751,1.014,121,24.092,48.148,8.686
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17991,2025-11-19 09:25:17.554219,CH,Zurich,47.377,8.542,52.120,71.160,35.405,7.752,39.811,0.878,104,32.556,31.372,2.787
17993,2025-11-19 11:25:17.554219,CH,Zurich,47.377,8.542,76.613,37.495,29.662,5.419,57.042,1.103,153,20.437,79.602,2.663
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660